config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'sales#new'

  resources :sales, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
# frozen_string_literal: true

class Sale < ApplicationRecord
  before_save :normalize_item_price, if: :item_price

  validates :id, uniqueness: true

  private

  def normalize_item_price
    self.item_price = item_price.round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  def index
    @total_gross_income = Sale.sum('item_price * purchase_count')
  end

  def new
    @sale = Sale.new
  end

  def create
    sales = Services::CSVParser.new(file: params[:sales][:file]).call

    sale_form = Forms::Sale.new(sales: sales)

    if sale_form.save
      redirect_to sales_path, format: :html
    else
      redirect_to new_sale_url, format: :html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuuvem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_with url: sales_url, multipart: true do %>
  <p class="field">
    <%= file_field_tag "sales[file]" %>
  </p>

  <p class="actions">
    <%= submit_tag %>
  </p>
<% end %>

app/views/sales/index.html.erb
<p>
  <strong>Total gross income:</strong>
  <%= "$ #{'%.2f' % @total_gross_income}" %>
</p>

<%= link_to 'New sales', root_path %>

app/views/sales/new.html.erb
<h1>New Sales</h1>

<%= render 'form' %>

<%= link_to 'Total gross income', sales_path %>